---
# Infrastructure components playbook
- name: Install Infrastructure Components
  hosts: all
  become: yes
  
  roles:
    - role: base
      tags: ['base', 'infrastructure']
    
    - role: apt_updates
      tags: ['apt_updates', 'infrastructure']
    
    - role: kubectl
      tags: ['kubectl', 'infrastructure']
    
    - role: helm
      tags: ['helm', 'infrastructure']
    
    - role: minikube
      tags: ['minikube', 'infrastructure']
    
    - role: tailscale
      tags: ['tailscale', 'infrastructure']
